#eureka:
#  client:
#    fetch-registry: true
#    healthcheck:
#      enabled: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#  instance:
#    hostname: localhost
server:
    port: 9091
spring:
    application:
        name: ORDER-SERVICE
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/micro_services
        username: root
        password : Password@123
    jpa:
     hibernate:
       ddl-auto: update
     generate-ddl: true
     show-sql: true
     database-platform: org.hibernate.dialect.MySQL8Dialect
    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic -name : order-service-topic
            
            
            
            
            